name: Build tests

on: [push]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        type: [debug, release]
        include:
          - type: debug
            afat: assembleAfatDebug
          - type: release
            afat: assembleAfatRelease
    steps:
      - name: Checkout.
        uses: actions/checkout@v3.1.0
        with:
          submodules: true

      - name: Setup Java.
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Setup NDK.
        uses: nttld/setup-ndk@v1.4.2
        id: setup-ndk
        with:
          ndk-version: r21e
          link-to-sdk: true

      - name: Build.
        run: |
          ./gradlew ${{ matrix.afat }}

      - name: Attach debug APK file
        uses: actions/upload-artifact@v4
        with:
          name: debug_apks
          path: |
            ./TMessagesProj_App/build/outputs/apk/afat/debug/*

      - name: Attach release APK file
        uses: actions/upload-artifact@v4
        with:
          name: release_apks
          path: |
            ./TMessagesProj_App/build/outputs/apk/afat/release/*
